sudo: required
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - python3 -m pip install --upgrade pip setuptools wheel
install:
  - pip3 install git+https://github.com/nextstrain/cli
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
script:
  - mkdir -p data/
  - cp -v example_data/zika.fasta data/
  - nextstrain build .
